### ISSUE TITLE
GROUPINGS-446 Angluar Error Code displayed

### ISSUE THREAD

**Issue by zakgilbert** [uhawaii-system-its-ti-iam/uh-groupings-ui#121]
## GROUPINGS-446 Angluar Error Code displayed
The error code is display when loading the admin and groupings pages

![bug](https://user-images.githubusercontent.com/26912258/63907340-c05c0e00-c9b6-11e9-8d86-9ac5d9da3e50.png)

**Comment by mhodgesatuh** [comment]
Can we close this since the corresponding JIRA ticket is closed?
